[install]
state = enabled
is_configured = 0

[launcher]
author = splunkbase@ba.id.au
version = 1.0.4
description = Prisma Cloud Audit Data Input

[package]
id = TA_prismacloud_audit

[id]
name = TA_prismacloud_audit
version = 1.0.4

[ui]
label = Prisma Cloud Audit
is_visible = 0
